

final Map response = {
  "playlist_name": "Songs to sing in the car",
  "href": "https://api.spotify.com/v1/playlists/37i9dQZF1DWWMOmoXKqHTD/tracks?offset=0&limit=100&locale=es-ES,es;q=0.9",
  "items": [
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/23fqKkggKUBHNkbKtXEls4"
              },
              "href": "https://api.spotify.com/v1/artists/23fqKkggKUBHNkbKtXEls4",
              "id": "23fqKkggKUBHNkbKtXEls4",
              "name": "Kygo",
              "type": "artist",
              "uri": "spotify:artist:23fqKkggKUBHNkbKtXEls4"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/5JYo7gm2dkyLLlWHjxS7Dy"
              },
              "href": "https://api.spotify.com/v1/artists/5JYo7gm2dkyLLlWHjxS7Dy",
              "id": "5JYo7gm2dkyLLlWHjxS7Dy",
              "name": "Sandro Cavazza",
              "type": "artist",
              "uri": "spotify:artist:5JYo7gm2dkyLLlWHjxS7Dy"
            }
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/6nAjd2MlBY1f1mNu6BsWLO"
          },
          "href": "https://api.spotify.com/v1/albums/6nAjd2MlBY1f1mNu6BsWLO",
          "id": "6nAjd2MlBY1f1mNu6BsWLO",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27382c80d6ec5b001d9ae49564d",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0282c80d6ec5b001d9ae49564d",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485182c80d6ec5b001d9ae49564d",
              "width": 64
            }
          ],
          "name": "Happy Now",
          "release_date": "2018-10-26",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:6nAjd2MlBY1f1mNu6BsWLO"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/23fqKkggKUBHNkbKtXEls4"
            },
            "href": "https://api.spotify.com/v1/artists/23fqKkggKUBHNkbKtXEls4",
            "id": "23fqKkggKUBHNkbKtXEls4",
            "name": "Kygo",
            "type": "artist",
            "uri": "spotify:artist:23fqKkggKUBHNkbKtXEls4"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5JYo7gm2dkyLLlWHjxS7Dy"
            },
            "href": "https://api.spotify.com/v1/artists/5JYo7gm2dkyLLlWHjxS7Dy",
            "id": "5JYo7gm2dkyLLlWHjxS7Dy",
            "name": "Sandro Cavazza",
            "type": "artist",
            "uri": "spotify:artist:5JYo7gm2dkyLLlWHjxS7Dy"
          }
        ],
        
        "disc_number": 1,
        "duration_ms": 211362,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "SEBGA1803418"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/14sOS5L36385FJ3OL8hew4"
        },
        "href": "https://api.spotify.com/v1/tracks/14sOS5L36385FJ3OL8hew4",
        "id": "14sOS5L36385FJ3OL8hew4",
        "is_local": false,
        "name": "Happy Now",
        "popularity": 72,
        "preview_url": "https://p.scdn.co/mp3-preview/a2c9677593d52774f89c7d2dd2e810ba4faac01c?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:14sOS5L36385FJ3OL8hew4"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6t1gpxYbY8OlLA7D2RiikQ"
              },
              "href": "https://api.spotify.com/v1/artists/6t1gpxYbY8OlLA7D2RiikQ",
              "id": "6t1gpxYbY8OlLA7D2RiikQ",
              "name": "Loud Luxury",
              "type": "artist",
              "uri": "spotify:artist:6t1gpxYbY8OlLA7D2RiikQ"
            }
          ],
          
          "external_urls": {
            "spotify": "https://open.spotify.com/album/5IwDFhelg9o8vrPNlYDpQR"
          },
          "href": "https://api.spotify.com/v1/albums/5IwDFhelg9o8vrPNlYDpQR",
          "id": "5IwDFhelg9o8vrPNlYDpQR",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273c85a86599e5e237504221b1f",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02c85a86599e5e237504221b1f",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851c85a86599e5e237504221b1f",
              "width": 64
            }
          ],
          "name": "Body",
          "release_date": "2017-10-27",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:5IwDFhelg9o8vrPNlYDpQR"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6t1gpxYbY8OlLA7D2RiikQ"
            },
            "href": "https://api.spotify.com/v1/artists/6t1gpxYbY8OlLA7D2RiikQ",
            "id": "6t1gpxYbY8OlLA7D2RiikQ",
            "name": "Loud Luxury",
            "type": "artist",
            "uri": "spotify:artist:6t1gpxYbY8OlLA7D2RiikQ"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5uEeqYFuIChoWKy34jp8xE"
            },
            "href": "https://api.spotify.com/v1/artists/5uEeqYFuIChoWKy34jp8xE",
            "id": "5uEeqYFuIChoWKy34jp8xE",
            "name": "Brando",
            "type": "artist",
            "uri": "spotify:artist:5uEeqYFuIChoWKy34jp8xE"
          }
        ],
        "disc_number": 1,
        "duration_ms": 163216,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "NLF711710457"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/3jvpPbTJqfyKvEOtOsn83m"
        },
        "href": "https://api.spotify.com/v1/tracks/3jvpPbTJqfyKvEOtOsn83m",
        "id": "3jvpPbTJqfyKvEOtOsn83m",
        "is_local": false,
        "name": "Body",
        "popularity": 61,
        "preview_url": "https://p.scdn.co/mp3-preview/cc8dc2d90a923e024f1c71dec1cd4f0a8650a1cc?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:3jvpPbTJqfyKvEOtOsn83m"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2X97ZAqRKRMYFIDqtvGgGc"
              },
              "href": "https://api.spotify.com/v1/artists/2X97ZAqRKRMYFIDqtvGgGc",
              "id": "2X97ZAqRKRMYFIDqtvGgGc",
              "name": "Silk City",
              "type": "artist",
              "uri": "spotify:artist:2X97ZAqRKRMYFIDqtvGgGc"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we"
              },
              "href": "https://api.spotify.com/v1/artists/6M2wZ9GZgrQXHCFfjv46we",
              "id": "6M2wZ9GZgrQXHCFfjv46we",
              "name": "Dua Lipa",
              "type": "artist",
              "uri": "spotify:artist:6M2wZ9GZgrQXHCFfjv46we"
            }
          ],
          
          "external_urls": {
            "spotify": "https://open.spotify.com/album/429B3se6xtZuvblNnS2iy7"
          },
          "href": "https://api.spotify.com/v1/albums/429B3se6xtZuvblNnS2iy7",
          "id": "429B3se6xtZuvblNnS2iy7",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2735ea1a511549bc05ff20fdedf",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e025ea1a511549bc05ff20fdedf",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048515ea1a511549bc05ff20fdedf",
              "width": 64
            }
          ],
          "name": "Electricity (with Dua Lipa)",
          "release_date": "2018-09-06",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:429B3se6xtZuvblNnS2iy7"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2X97ZAqRKRMYFIDqtvGgGc"
            },
            "href": "https://api.spotify.com/v1/artists/2X97ZAqRKRMYFIDqtvGgGc",
            "id": "2X97ZAqRKRMYFIDqtvGgGc",
            "name": "Silk City",
            "type": "artist",
            "uri": "spotify:artist:2X97ZAqRKRMYFIDqtvGgGc"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we"
            },
            "href": "https://api.spotify.com/v1/artists/6M2wZ9GZgrQXHCFfjv46we",
            "id": "6M2wZ9GZgrQXHCFfjv46we",
            "name": "Dua Lipa",
            "type": "artist",
            "uri": "spotify:artist:6M2wZ9GZgrQXHCFfjv46we"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5fMUXHkw8R8eOP2RNVYEZX"
            },
            "href": "https://api.spotify.com/v1/artists/5fMUXHkw8R8eOP2RNVYEZX",
            "id": "5fMUXHkw8R8eOP2RNVYEZX",
            "name": "Diplo",
            "type": "artist",
            "uri": "spotify:artist:5fMUXHkw8R8eOP2RNVYEZX"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3hv9jJF3adDNsBSIQDqcjp"
            },
            "href": "https://api.spotify.com/v1/artists/3hv9jJF3adDNsBSIQDqcjp",
            "id": "3hv9jJF3adDNsBSIQDqcjp",
            "name": "Mark Ronson",
            "type": "artist",
            "uri": "spotify:artist:3hv9jJF3adDNsBSIQDqcjp"
          }
        ],
        
        "disc_number": 1,
        "duration_ms": 238173,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "USQX91802285"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5N4erncE7kuUccm7zEmwzk"
        },
        "href": "https://api.spotify.com/v1/tracks/5N4erncE7kuUccm7zEmwzk",
        "id": "5N4erncE7kuUccm7zEmwzk",
        "is_local": false,
        "name": "Electricity (with Dua Lipa)",
        "popularity": 75,
        "preview_url": "https://p.scdn.co/mp3-preview/d4362730866e97d2e89776ceea7ad31cc5a44541?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:5N4erncE7kuUccm7zEmwzk"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/5jAMCwdNHWr7JThxtMuEyy"
              },
              "href": "https://api.spotify.com/v1/artists/5jAMCwdNHWr7JThxtMuEyy",
              "id": "5jAMCwdNHWr7JThxtMuEyy",
              "name": "NOTD",
              "type": "artist",
              "uri": "spotify:artist:5jAMCwdNHWr7JThxtMuEyy"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4bL2B6hmLlMWnUEZnorEtG"
              },
              "href": "https://api.spotify.com/v1/artists/4bL2B6hmLlMWnUEZnorEtG",
              "id": "4bL2B6hmLlMWnUEZnorEtG",
              "name": "Felix Jaehn",
              "type": "artist",
              "uri": "spotify:artist:4bL2B6hmLlMWnUEZnorEtG"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0rlKkLkpsCnJbZethGBfAk"
              },
              "href": "https://api.spotify.com/v1/artists/0rlKkLkpsCnJbZethGBfAk",
              "id": "0rlKkLkpsCnJbZethGBfAk",
              "name": "Captain Cuts",
              "type": "artist",
              "uri": "spotify:artist:0rlKkLkpsCnJbZethGBfAk"
            }
          ],
          
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4ZIaWbFnkMozASM1CA59K6"
          },
          "href": "https://api.spotify.com/v1/albums/4ZIaWbFnkMozASM1CA59K6",
          "id": "4ZIaWbFnkMozASM1CA59K6",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273e1f3e850068761db3477a24a",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02e1f3e850068761db3477a24a",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851e1f3e850068761db3477a24a",
              "width": 64
            }
          ],
          "name": "So Close (feat. Georgia Ku)",
          "release_date": "2018-11-02",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:4ZIaWbFnkMozASM1CA59K6"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5jAMCwdNHWr7JThxtMuEyy"
            },
            "href": "https://api.spotify.com/v1/artists/5jAMCwdNHWr7JThxtMuEyy",
            "id": "5jAMCwdNHWr7JThxtMuEyy",
            "name": "NOTD",
            "type": "artist",
            "uri": "spotify:artist:5jAMCwdNHWr7JThxtMuEyy"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4bL2B6hmLlMWnUEZnorEtG"
            },
            "href": "https://api.spotify.com/v1/artists/4bL2B6hmLlMWnUEZnorEtG",
            "id": "4bL2B6hmLlMWnUEZnorEtG",
            "name": "Felix Jaehn",
            "type": "artist",
            "uri": "spotify:artist:4bL2B6hmLlMWnUEZnorEtG"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/0rlKkLkpsCnJbZethGBfAk"
            },
            "href": "https://api.spotify.com/v1/artists/0rlKkLkpsCnJbZethGBfAk",
            "id": "0rlKkLkpsCnJbZethGBfAk",
            "name": "Captain Cuts",
            "type": "artist",
            "uri": "spotify:artist:0rlKkLkpsCnJbZethGBfAk"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5mYakBbBzPMQTfkVMIgiDM"
            },
            "href": "https://api.spotify.com/v1/artists/5mYakBbBzPMQTfkVMIgiDM",
            "id": "5mYakBbBzPMQTfkVMIgiDM",
            "name": "Georgia Ku",
            "type": "artist",
            "uri": "spotify:artist:5mYakBbBzPMQTfkVMIgiDM"
          }
        ],
        
        "disc_number": 1,
        "duration_ms": 190302,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "SEUM71800604"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/7FjZU7XFs7P9jHI9Z0yRhK"
        },
        "href": "https://api.spotify.com/v1/tracks/7FjZU7XFs7P9jHI9Z0yRhK",
        "id": "7FjZU7XFs7P9jHI9Z0yRhK",
        "is_local": false,
        "name": "So Close",
        "popularity": 73,
        "preview_url": "https://p.scdn.co/mp3-preview/43f9160e3d3cef5812bb1a778d1c3d759ae8b29e?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:7FjZU7XFs7P9jHI9Z0yRhK"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/67hb7towEyKvt5Z8Bx306c"
              },
              "href": "https://api.spotify.com/v1/artists/67hb7towEyKvt5Z8Bx306c",
              "id": "67hb7towEyKvt5Z8Bx306c",
              "name": "Empire of the Sun",
              "type": "artist",
              "uri": "spotify:artist:67hb7towEyKvt5Z8Bx306c"
            }
          ],
          
          "external_urls": {
            "spotify": "https://open.spotify.com/album/5B6XfyHHYawyLkEvNvhSPh"
          },
          "href": "https://api.spotify.com/v1/albums/5B6XfyHHYawyLkEvNvhSPh",
          "id": "5B6XfyHHYawyLkEvNvhSPh",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273f3aa0e6ca22a382007f61e4d",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02f3aa0e6ca22a382007f61e4d",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851f3aa0e6ca22a382007f61e4d",
              "width": 64
            }
          ],
          "name": "Walking On A Dream (10th Anniversary Edition)",
          "release_date": "2008-10-03",
          "release_date_precision": "day",
          "total_tracks": 16,
          "type": "album",
          "uri": "spotify:album:5B6XfyHHYawyLkEvNvhSPh"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/67hb7towEyKvt5Z8Bx306c"
            },
            "href": "https://api.spotify.com/v1/artists/67hb7towEyKvt5Z8Bx306c",
            "id": "67hb7towEyKvt5Z8Bx306c",
            "name": "Empire of the Sun",
            "type": "artist",
            "uri": "spotify:artist:67hb7towEyKvt5Z8Bx306c"
          }
        ],
        
        "disc_number": 1,
        "duration_ms": 198440,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "AUEI10800039"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5r5cp9IpziiIsR6b93vcnQ"
        },
        "href": "https://api.spotify.com/v1/tracks/5r5cp9IpziiIsR6b93vcnQ",
        "id": "5r5cp9IpziiIsR6b93vcnQ",
        "is_local": false,
        "name": "Walking On A Dream",
        "popularity": 80,
        "preview_url": "https://p.scdn.co/mp3-preview/8701b4cfc0ff5013dc7ed3f7701d9d6399f26a99?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 2,
        "type": "track",
        "uri": "spotify:track:5r5cp9IpziiIsR6b93vcnQ"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6USv9qhCn6zfxlBQIYJ9qs"
              },
              "href": "https://api.spotify.com/v1/artists/6USv9qhCn6zfxlBQIYJ9qs",
              "id": "6USv9qhCn6zfxlBQIYJ9qs",
              "name": "Dominic Fike",
              "type": "artist",
              "uri": "spotify:artist:6USv9qhCn6zfxlBQIYJ9qs"
            }
          ],
          
          "external_urls": {
            "spotify": "https://open.spotify.com/album/1DNx0H5ZX1ax3yyRwtgT4S"
          },
          "href": "https://api.spotify.com/v1/albums/1DNx0H5ZX1ax3yyRwtgT4S",
          "id": "1DNx0H5ZX1ax3yyRwtgT4S",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2734a42166d927b3acce345c5c0",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e024a42166d927b3acce345c5c0",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048514a42166d927b3acce345c5c0",
              "width": 64
            }
          ],
          "name": "Don't Forget About Me, Demos",
          "release_date": "2018-10-16",
          "release_date_precision": "day",
          "total_tracks": 6,
          "type": "album",
          "uri": "spotify:album:1DNx0H5ZX1ax3yyRwtgT4S"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6USv9qhCn6zfxlBQIYJ9qs"
            },
            "href": "https://api.spotify.com/v1/artists/6USv9qhCn6zfxlBQIYJ9qs",
            "id": "6USv9qhCn6zfxlBQIYJ9qs",
            "name": "Dominic Fike",
            "type": "artist",
            "uri": "spotify:artist:6USv9qhCn6zfxlBQIYJ9qs"
          }
        ],
        
        "disc_number": 1,
        "duration_ms": 177666,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "USQX91802455"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/1tNJrcVe6gwLEiZCtprs1u"
        },
        "href": "https://api.spotify.com/v1/tracks/1tNJrcVe6gwLEiZCtprs1u",
        "id": "1tNJrcVe6gwLEiZCtprs1u",
        "is_local": false,
        "name": "3 Nights",
        "popularity": 79,
        "preview_url": "https://p.scdn.co/mp3-preview/4541d9fdce0a1a70103690863356bee8ca05d02b?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:1tNJrcVe6gwLEiZCtprs1u"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/3t5xRXzsuZmMDkQzgOX35S"
              },
              "href": "https://api.spotify.com/v1/artists/3t5xRXzsuZmMDkQzgOX35S",
              "id": "3t5xRXzsuZmMDkQzgOX35S",
              "name": "Robin Schulz",
              "type": "artist",
              "uri": "spotify:artist:3t5xRXzsuZmMDkQzgOX35S"
            }
          ],
          
          "external_urls": {
            "spotify": "https://open.spotify.com/album/5XyJzEROSmup2TcWmVjTIt"
          },
          "href": "https://api.spotify.com/v1/albums/5XyJzEROSmup2TcWmVjTIt",
          "id": "5XyJzEROSmup2TcWmVjTIt",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2733c9047f9aa5d0d1e03827039",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e023c9047f9aa5d0d1e03827039",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048513c9047f9aa5d0d1e03827039",
              "width": 64
            }
          ],
          "name": "Sugar",
          "release_date": "2015-09-25",
          "release_date_precision": "day",
          "total_tracks": 15,
          "type": "album",
          "uri": "spotify:album:5XyJzEROSmup2TcWmVjTIt"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3t5xRXzsuZmMDkQzgOX35S"
            },
            "href": "https://api.spotify.com/v1/artists/3t5xRXzsuZmMDkQzgOX35S",
            "id": "3t5xRXzsuZmMDkQzgOX35S",
            "name": "Robin Schulz",
            "type": "artist",
            "uri": "spotify:artist:3t5xRXzsuZmMDkQzgOX35S"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5X1JzPIIonP3u9lA580pPT"
            },
            "href": "https://api.spotify.com/v1/artists/5X1JzPIIonP3u9lA580pPT",
            "id": "5X1JzPIIonP3u9lA580pPT",
            "name": "Francesco Yates",
            "type": "artist",
            "uri": "spotify:artist:5X1JzPIIonP3u9lA580pPT"
          }
        ],
        
        "disc_number": 1,
        "duration_ms": 219043,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "DEA621501057"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5tf1VVWniHgryyumXyJM7w"
        },
        "href": "https://api.spotify.com/v1/tracks/5tf1VVWniHgryyumXyJM7w",
        "id": "5tf1VVWniHgryyumXyJM7w",
        "is_local": false,
        "name": "Sugar (feat. Francesco Yates)",
        "popularity": 79,
        "preview_url": "https://p.scdn.co/mp3-preview/c4b6941542e99f1a0cf480d6b1ed033be783a3fa?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 2,
        "type": "track",
        "uri": "spotify:track:5tf1VVWniHgryyumXyJM7w"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/7CajNmpbOovFoOoasH2HaY"
              },
              "href": "https://api.spotify.com/v1/artists/7CajNmpbOovFoOoasH2HaY",
              "id": "7CajNmpbOovFoOoasH2HaY",
              "name": "Calvin Harris",
              "type": "artist",
              "uri": "spotify:artist:7CajNmpbOovFoOoasH2HaY"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2wY79sveU1sp5g7SokKOiI"
              },
              "href": "https://api.spotify.com/v1/artists/2wY79sveU1sp5g7SokKOiI",
              "id": "2wY79sveU1sp5g7SokKOiI",
              "name": "Sam Smith",
              "type": "artist",
              "uri": "spotify:artist:2wY79sveU1sp5g7SokKOiI"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/3KedxarmBCyFBevnqQHy3P"
              },
              "href": "https://api.spotify.com/v1/artists/3KedxarmBCyFBevnqQHy3P",
              "id": "3KedxarmBCyFBevnqQHy3P",
              "name": "Jessie Reyez",
              "type": "artist",
              "uri": "spotify:artist:3KedxarmBCyFBevnqQHy3P"
            }
          ],
          
          "external_urls": {
            "spotify": "https://open.spotify.com/album/2tpWgbBdzjkaJVJzR4T8y1"
          },
          "href": "https://api.spotify.com/v1/albums/2tpWgbBdzjkaJVJzR4T8y1",
          "id": "2tpWgbBdzjkaJVJzR4T8y1",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273ccdcbd450e42fc7b27a82a1f",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02ccdcbd450e42fc7b27a82a1f",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851ccdcbd450e42fc7b27a82a1f",
              "width": 64
            }
          ],
          "name": "Promises (with Sam Smith)",
          "release_date": "2018-08-17",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:2tpWgbBdzjkaJVJzR4T8y1"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/7CajNmpbOovFoOoasH2HaY"
            },
            "href": "https://api.spotify.com/v1/artists/7CajNmpbOovFoOoasH2HaY",
            "id": "7CajNmpbOovFoOoasH2HaY",
            "name": "Calvin Harris",
            "type": "artist",
            "uri": "spotify:artist:7CajNmpbOovFoOoasH2HaY"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2wY79sveU1sp5g7SokKOiI"
            },
            "href": "https://api.spotify.com/v1/artists/2wY79sveU1sp5g7SokKOiI",
            "id": "2wY79sveU1sp5g7SokKOiI",
            "name": "Sam Smith",
            "type": "artist",
            "uri": "spotify:artist:2wY79sveU1sp5g7SokKOiI"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3KedxarmBCyFBevnqQHy3P"
            },
            "href": "https://api.spotify.com/v1/artists/3KedxarmBCyFBevnqQHy3P",
            "id": "3KedxarmBCyFBevnqQHy3P",
            "name": "Jessie Reyez",
            "type": "artist",
            "uri": "spotify:artist:3KedxarmBCyFBevnqQHy3P"
          }
        ],
        
        "disc_number": 1,
        "duration_ms": 213309,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "GBARL1801049"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5N5k9nd479b1xpDZ4usjrg"
        },
        "href": "https://api.spotify.com/v1/tracks/5N5k9nd479b1xpDZ4usjrg",
        "id": "5N5k9nd479b1xpDZ4usjrg",
        "is_local": false,
        "name": "Promises (with Sam Smith)",
        "popularity": 78,
        "preview_url": "https://p.scdn.co/mp3-preview/c78e0a33c394091314b35a2fd42b0102cc8fb1cd?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:5N5k9nd479b1xpDZ4usjrg"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/64KEffDW9EtZ1y2vBYgq8T"
              },
              "href": "https://api.spotify.com/v1/artists/64KEffDW9EtZ1y2vBYgq8T",
              "id": "64KEffDW9EtZ1y2vBYgq8T",
              "name": "Marshmello",
              "type": "artist",
              "uri": "spotify:artist:64KEffDW9EtZ1y2vBYgq8T"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/7EQ0qTo7fWT7DPxmxtSYEc"
              },
              "href": "https://api.spotify.com/v1/artists/7EQ0qTo7fWT7DPxmxtSYEc",
              "id": "7EQ0qTo7fWT7DPxmxtSYEc",
              "name": "Bastille",
              "type": "artist",
              "uri": "spotify:artist:7EQ0qTo7fWT7DPxmxtSYEc"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/78EicdHZr5XBWD7llEZ1Jh"
          },
          "href": "https://api.spotify.com/v1/albums/78EicdHZr5XBWD7llEZ1Jh",
          "id": "78EicdHZr5XBWD7llEZ1Jh",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27304bfd5a5fd5aa6ca648f66aa",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0204bfd5a5fd5aa6ca648f66aa",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485104bfd5a5fd5aa6ca648f66aa",
              "width": 64
            }
          ],
          "name": "Happier",
          "release_date": "2018-08-17",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:78EicdHZr5XBWD7llEZ1Jh"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/64KEffDW9EtZ1y2vBYgq8T"
            },
            "href": "https://api.spotify.com/v1/artists/64KEffDW9EtZ1y2vBYgq8T",
            "id": "64KEffDW9EtZ1y2vBYgq8T",
            "name": "Marshmello",
            "type": "artist",
            "uri": "spotify:artist:64KEffDW9EtZ1y2vBYgq8T"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/7EQ0qTo7fWT7DPxmxtSYEc"
            },
            "href": "https://api.spotify.com/v1/artists/7EQ0qTo7fWT7DPxmxtSYEc",
            "id": "7EQ0qTo7fWT7DPxmxtSYEc",
            "name": "Bastille",
            "type": "artist",
            "uri": "spotify:artist:7EQ0qTo7fWT7DPxmxtSYEc"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 214289,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "USUG11801651"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/2dpaYNEQHiRxtZbfNsse99"
        },
        "href": "https://api.spotify.com/v1/tracks/2dpaYNEQHiRxtZbfNsse99",
        "id": "2dpaYNEQHiRxtZbfNsse99",
        "is_local": false,
        "name": "Happier",
        "popularity": 85,
        "preview_url": "https://p.scdn.co/mp3-preview/f59db3db3ac00c3531023b6c486bce473715e220?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:2dpaYNEQHiRxtZbfNsse99"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we"
              },
              "href": "https://api.spotify.com/v1/artists/6M2wZ9GZgrQXHCFfjv46we",
              "id": "6M2wZ9GZgrQXHCFfjv46we",
              "name": "Dua Lipa",
              "type": "artist",
              "uri": "spotify:artist:6M2wZ9GZgrQXHCFfjv46we"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0ix3XtPV1LwmZADsprKxcp"
          },
          "href": "https://api.spotify.com/v1/albums/0ix3XtPV1LwmZADsprKxcp",
          "id": "0ix3XtPV1LwmZADsprKxcp",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2738583df1a14bea9175f9ac520",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e028583df1a14bea9175f9ac520",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048518583df1a14bea9175f9ac520",
              "width": 64
            }
          ],
          "name": "Don't Start Now",
          "release_date": "2019-10-31",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:0ix3XtPV1LwmZADsprKxcp"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we"
            },
            "href": "https://api.spotify.com/v1/artists/6M2wZ9GZgrQXHCFfjv46we",
            "id": "6M2wZ9GZgrQXHCFfjv46we",
            "name": "Dua Lipa",
            "type": "artist",
            "uri": "spotify:artist:6M2wZ9GZgrQXHCFfjv46we"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 183290,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "GBAHT1901121"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/6WrI0LAC5M1Rw2MnX2ZvEg"
        },
        "href": "https://api.spotify.com/v1/tracks/6WrI0LAC5M1Rw2MnX2ZvEg",
        "id": "6WrI0LAC5M1Rw2MnX2ZvEg",
        "is_local": false,
        "name": "Don't Start Now",
        "popularity": 83,
        "preview_url": "https://p.scdn.co/mp3-preview/ed151225213380a41e5c4af00ff558e25b5875d1?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:6WrI0LAC5M1Rw2MnX2ZvEg"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
              },
              "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
              "id": "0TnOYISbd1XYRBk9myaseg",
              "name": "Pitbull",
              "type": "artist",
              "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4EUf4YyNjuXypWY6W5wEDm"
          },
          "href": "https://api.spotify.com/v1/albums/4EUf4YyNjuXypWY6W5wEDm",
          "id": "4EUf4YyNjuXypWY6W5wEDm",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2731e340d1480e7bb29a45e3bd7",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e021e340d1480e7bb29a45e3bd7",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048511e340d1480e7bb29a45e3bd7",
              "width": 64
            }
          ],
          "name": "Globalization",
          "release_date": "2014-11-21",
          "release_date_precision": "day",
          "total_tracks": 11,
          "type": "album",
          "uri": "spotify:album:4EUf4YyNjuXypWY6W5wEDm"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
            },
            "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
            "id": "0TnOYISbd1XYRBk9myaseg",
            "name": "Pitbull",
            "type": "artist",
            "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/21E3waRsmPlU7jZsS13rcj"
            },
            "href": "https://api.spotify.com/v1/artists/21E3waRsmPlU7jZsS13rcj",
            "id": "21E3waRsmPlU7jZsS13rcj",
            "name": "Ne-Yo",
            "type": "artist",
            "uri": "spotify:artist:21E3waRsmPlU7jZsS13rcj"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 229360,
        "episode": false,
        "explicit": true,
        "external_ids": {
          "isrc": "USRC11402647"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/2bJvI42r8EF3wxjOuDav4r"
        },
        "href": "https://api.spotify.com/v1/tracks/2bJvI42r8EF3wxjOuDav4r",
        "id": "2bJvI42r8EF3wxjOuDav4r",
        "is_local": false,
        "name": "Time of Our Lives",
        "popularity": 82,
        "preview_url": "https://p.scdn.co/mp3-preview/c7ee72511ef4733508b42f92de3e62ed4753e223?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:2bJvI42r8EF3wxjOuDav4r"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/7f5Zgnp2spUuuzKplmRkt7"
              },
              "href": "https://api.spotify.com/v1/artists/7f5Zgnp2spUuuzKplmRkt7",
              "id": "7f5Zgnp2spUuuzKplmRkt7",
              "name": "Lost Frequencies",
              "type": "artist",
              "uri": "spotify:artist:7f5Zgnp2spUuuzKplmRkt7"
            }
          ],
          "available_markets": [
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BF",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CD",
            "CG",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LV",
            "LY",
            "MA",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/6NQRmMazNOKi0IiIXlNzGh"
          },
          "href": "https://api.spotify.com/v1/albums/6NQRmMazNOKi0IiIXlNzGh",
          "id": "6NQRmMazNOKi0IiIXlNzGh",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273127e13a21108faeaecb19167",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02127e13a21108faeaecb19167",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851127e13a21108faeaecb19167",
              "width": 64
            }
          ],
          "name": "Alive And Feeling Fine",
          "release_date": "2019-10-04",
          "release_date_precision": "day",
          "total_tracks": 23,
          "type": "album",
          "uri": "spotify:album:6NQRmMazNOKi0IiIXlNzGh"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/7f5Zgnp2spUuuzKplmRkt7"
            },
            "href": "https://api.spotify.com/v1/artists/7f5Zgnp2spUuuzKplmRkt7",
            "id": "7f5Zgnp2spUuuzKplmRkt7",
            "name": "Lost Frequencies",
            "type": "artist",
            "uri": "spotify:artist:7f5Zgnp2spUuuzKplmRkt7"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/09JJrjk6Mr5ZYwk1mk7aEb"
            },
            "href": "https://api.spotify.com/v1/artists/09JJrjk6Mr5ZYwk1mk7aEb",
            "id": "09JJrjk6Mr5ZYwk1mk7aEb",
            "name": "Love Harder",
            "type": "artist",
            "uri": "spotify:artist:09JJrjk6Mr5ZYwk1mk7aEb"
          }
        ],
        "available_markets": [
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BF",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CD",
          "CG",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LV",
          "LY",
          "MA",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 183183,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "NLF711909044"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/4w5Grfxx5Rpup6mo5v6bW0"
        },
        "href": "https://api.spotify.com/v1/tracks/4w5Grfxx5Rpup6mo5v6bW0",
        "id": "4w5Grfxx5Rpup6mo5v6bW0",
        "is_local": false,
        "name": "Beat Of My Heart",
        "popularity": 62,
        "preview_url": "https://p.scdn.co/mp3-preview/64702056e8b3733203d4c9c7ea9d320a140c4fdb?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:4w5Grfxx5Rpup6mo5v6bW0"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/50OApTJurDusIo9dGTqSU4"
              },
              "href": "https://api.spotify.com/v1/artists/50OApTJurDusIo9dGTqSU4",
              "id": "50OApTJurDusIo9dGTqSU4",
              "name": "Lilly Wood and The Prick",
              "type": "artist",
              "uri": "spotify:artist:50OApTJurDusIo9dGTqSU4"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/3t5xRXzsuZmMDkQzgOX35S"
              },
              "href": "https://api.spotify.com/v1/artists/3t5xRXzsuZmMDkQzgOX35S",
              "id": "3t5xRXzsuZmMDkQzgOX35S",
              "name": "Robin Schulz",
              "type": "artist",
              "uri": "spotify:artist:3t5xRXzsuZmMDkQzgOX35S"
            }
          ],
          "available_markets": [
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FJ",
            "FM",
            "GA",
            "GD",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MD",
            "ME",
            "MG",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MW",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NP",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SC",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TR",
            "TT",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/6Ps0kbvAjuz75uK0uuZzWa"
          },
          "href": "https://api.spotify.com/v1/albums/6Ps0kbvAjuz75uK0uuZzWa",
          "id": "6Ps0kbvAjuz75uK0uuZzWa",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2730538d5d965798a403219a470",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e020538d5d965798a403219a470",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048510538d5d965798a403219a470",
              "width": 64
            }
          ],
          "name": "Prayer in C",
          "release_date": "2014-05-16",
          "release_date_precision": "day",
          "total_tracks": 2,
          "type": "album",
          "uri": "spotify:album:6Ps0kbvAjuz75uK0uuZzWa"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/50OApTJurDusIo9dGTqSU4"
            },
            "href": "https://api.spotify.com/v1/artists/50OApTJurDusIo9dGTqSU4",
            "id": "50OApTJurDusIo9dGTqSU4",
            "name": "Lilly Wood and The Prick",
            "type": "artist",
            "uri": "spotify:artist:50OApTJurDusIo9dGTqSU4"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3t5xRXzsuZmMDkQzgOX35S"
            },
            "href": "https://api.spotify.com/v1/artists/3t5xRXzsuZmMDkQzgOX35S",
            "id": "3t5xRXzsuZmMDkQzgOX35S",
            "name": "Robin Schulz",
            "type": "artist",
            "uri": "spotify:artist:3t5xRXzsuZmMDkQzgOX35S"
          }
        ],
        "available_markets": [
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FJ",
          "FM",
          "GA",
          "GD",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MD",
          "ME",
          "MG",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NP",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SC",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TR",
          "TT",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 189413,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "DEA621400286"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5fnA9mkIfScSqHIpeDyvck"
        },
        "href": "https://api.spotify.com/v1/tracks/5fnA9mkIfScSqHIpeDyvck",
        "id": "5fnA9mkIfScSqHIpeDyvck",
        "is_local": false,
        "name": "Prayer in C - Robin Schulz Radio Edit",
        "popularity": 73,
        "preview_url": "https://p.scdn.co/mp3-preview/58068691248c3b9a53eac46f9c8817ac11233913?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:5fnA9mkIfScSqHIpeDyvck"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2021-11-11T04:45:51Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6MDME20pz9RveH9rEXvrOM"
              },
              "href": "https://api.spotify.com/v1/artists/6MDME20pz9RveH9rEXvrOM",
              "id": "6MDME20pz9RveH9rEXvrOM",
              "name": "Clean Bandit",
              "type": "artist",
              "uri": "spotify:artist:6MDME20pz9RveH9rEXvrOM"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BW",
            "BY",
            "BZ",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GD",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TR",
            "TT",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0dNt3MfPrvj6mHmajSuahw"
          },
          "href": "https://api.spotify.com/v1/albums/0dNt3MfPrvj6mHmajSuahw",
          "id": "0dNt3MfPrvj6mHmajSuahw",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2735ef315d54fd701725176292e",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e025ef315d54fd701725176292e",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048515ef315d54fd701725176292e",
              "width": 64
            }
          ],
          "name": "New Eyes",
          "release_date": "2014-06-02",
          "release_date_precision": "day",
          "total_tracks": 16,
          "type": "album",
          "uri": "spotify:album:0dNt3MfPrvj6mHmajSuahw"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6MDME20pz9RveH9rEXvrOM"
            },
            "href": "https://api.spotify.com/v1/artists/6MDME20pz9RveH9rEXvrOM",
            "id": "6MDME20pz9RveH9rEXvrOM",
            "name": "Clean Bandit",
            "type": "artist",
            "uri": "spotify:artist:6MDME20pz9RveH9rEXvrOM"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4ScCswdRlyA23odg9thgIO"
            },
            "href": "https://api.spotify.com/v1/artists/4ScCswdRlyA23odg9thgIO",
            "id": "4ScCswdRlyA23odg9thgIO",
            "name": "Jess Glynne",
            "type": "artist",
            "uri": "spotify:artist:4ScCswdRlyA23odg9thgIO"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BW",
          "BY",
          "BZ",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GD",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TR",
          "TT",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 227833,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "GBAHS1300498"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/61dCUoMCg28qEBzrW6htYM"
        },
        "href": "https://api.spotify.com/v1/tracks/61dCUoMCg28qEBzrW6htYM",
        "id": "61dCUoMCg28qEBzrW6htYM",
        "is_local": false,
        "name": "Rather Be (feat. Jess Glynne)",
        "popularity": 72,
        "preview_url": "https://p.scdn.co/mp3-preview/a9d9d2d68603e22dd2f04693c8e29e4f5823e09f?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:61dCUoMCg28qEBzrW6htYM"
      },
      "video_thumbnail": {
        "url": null
      }
    },
  ],
  "limit": 100,
  "next": null,
  "offset": 0,
  "previous": null,
  "total": 100
  };